IOU_THS = 0.01
NMS_THS = 12
TOP_K = 500
PERSON_WIDTH = 30
PERSON_HEIGHT = 160
BODY_HEIGHT = 1600
BODY_WIDTH = 150
BBOX_LEN = 5
PROJ_Z_VAL = 0
COLORS = ['white', 'lightcoral', 'red', 'gray', 'pink', 'cyan', 'mediumorchid', 'orange', 'gold']